sonar.projectKey=motionet_pmo-agents_2217d854-e44b-463c-9843-74e1fb5c19cb
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/build/**,**/coverage/**
